[package]
edition.workspace = true
license-file.workspace = true
name = "katana-vrf"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
ark-ec = "0.4.2"
ark-ff = "0.4.2"
axum.workspace = true
clap.workspace = true
chrono.workspace = true
prost.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet.workspace = true
starknet-crypto.workspace = true
stark-vrf.workspace = true
tokio.workspace = true
tower-http = { workspace = true, features = ["trace"] }
tracing.workspace = true
tracing-subscriber = "0.3"
url.workspace = true

cainome.workspace = true
cainome-cairo-serde.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
