[package]
edition.workspace = true
license.workspace = true
name = "katana-pipeline"
repository.workspace = true
version.workspace = true

[dependencies]
katana-metrics.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
katana-provider-api.workspace = true
katana-stage.workspace = true

futures.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
katana-provider = { workspace = true, features = [ "test-utils" ] }
async-trait.workspace = true
anyhow.workspace = true
