[package]
description = "Katana RPC Implementation."
edition.workspace = true
license-file.workspace = true
name = "katana-rpc-server"
repository.workspace = true
version.workspace = true

[dependencies]
katana-core.workspace = true
katana-chain-spec.workspace = true
katana-executor.workspace = true
katana-explorer = { workspace = true, features = [ "jsonrpsee" ], optional = true }
katana-metrics.workspace = true
katana-pool.workspace = true
katana-primitives.workspace = true
katana-genesis = { workspace = true, optional = true }
katana-provider = { workspace = true, features = [ "test-utils" ] }
katana-rpc-api = { workspace = true, features = [ "client" ] }
katana-rpc-types.workspace = true
katana-rpc-types-builder.workspace = true
katana-tasks.workspace = true
katana-gas-price-oracle.workspace = true
katana-tracing.workspace = true

anyhow.workspace = true
auto_impl.workspace = true
http.workspace = true
jsonrpsee = { workspace = true, features = [ "client", "server" ] }
metrics.workspace = true
reqwest = { workspace = true, optional = true }
serde_json.workspace = true
starknet = { workspace = true, optional = true }
starknet-paymaster = { package = "starknet", git = "https://github.com/xJonathanLEI/starknet-rs", tag = "starknet/v0.17.0", optional = true }
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http = { workspace = true, features = [ "cors", "trace" ] }
tracing.workspace = true

cainome = { workspace = true, optional = true }
cainome-cairo-serde = { workspace = true, optional = true }
cartridge = { workspace = true, optional = true }
paymaster-rpc = { workspace = true, optional = true }
url = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

katana-tee = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
starknet-types-core = { workspace = true, optional = true }

[dev-dependencies]
katana-chain-spec.workspace = true
katana-contracts.workspace = true
katana-messaging.workspace = true
katana-node = { workspace = true, features = [ "cartridge" ] }
katana-rpc-api = { workspace = true, features = [ "client" ] }
katana-rpc-client.workspace = true
katana-trie.workspace = true
katana-genesis.workspace = true
katana-utils = { workspace = true, features = ["node"] }

alloy-contract = { workspace = true, default-features = false }
alloy-node-bindings = "1.0.24"
alloy-primitives = { workspace = true, features = [ "serde" ] }
alloy-provider = { workspace = true, default-features = false, features = [ "anvil-node", "reqwest", "reqwest-rustls-tls" ] }
alloy-sol-types.workspace = true

assert_matches.workspace = true
cainome.workspace = true
cairo-lang-starknet-classes.workspace = true
indexmap.workspace = true
jsonrpsee = { workspace = true, features = [ "client" ] }
num-traits.workspace = true
rand.workspace = true
rstest.workspace = true
serde.workspace = true
serde_json.workspace = true
similar-asserts.workspace = true
starknet.workspace = true
stark-vrf.workspace = true
tempfile.workspace = true
tokio.workspace = true
url.workspace = true

[features]
paymaster = [
	"dep:paymaster-rpc",
	"dep:url",
	"dep:serde",
	"katana-rpc-api/paymaster",
]
vrf = [
	"paymaster",
]
cartridge = [
	"dep:cainome",
	"dep:cainome-cairo-serde",
	"dep:cartridge",
	"dep:katana-genesis",
	"dep:reqwest",
	"dep:starknet",
	"dep:starknet-paymaster",
	"paymaster",
	"vrf",
	"katana-rpc-api/cartridge",
]
explorer = ["dep:katana-explorer"]
tee = [
	"dep:katana-tee",
	"dep:hex",
	"dep:starknet-types-core",
	"katana-rpc-api/tee",
]
