[package]
name = "katana-sharding-node"
edition.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
katana-node-config.workspace = true
katana-chain-spec.workspace = true
katana-core.workspace = true
katana-db.workspace = true
katana-executor.workspace = true
katana-gateway-server.workspace = true
katana-gas-price-oracle.workspace = true
katana-grpc = { workspace = true, optional = true }
katana-messaging.workspace = true
katana-metrics.workspace = true
katana-pool.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
katana-rpc-server.workspace = true
katana-rpc-api.workspace = true
katana-rpc-client.workspace = true
katana-rpc-types.workspace = true
katana-sharding.workspace = true
katana-stage.workspace = true
katana-tasks.workspace = true
katana-tee = { workspace = true, optional = true }

anyhow.workspace = true
num-traits.workspace = true
futures.workspace = true
http.workspace = true
tokio.workspace = true
parking_lot.workspace = true
jsonrpsee.workspace = true
serde.workspace = true
tracing.workspace = true
url.workspace = true
