[package]
edition.workspace = true
license.workspace = true
name = "katana-migration"
repository.workspace = true
version.workspace = true

[dependencies]
katana-chain-spec.workspace = true
katana-core.workspace = true
katana-db.workspace = true
katana-executor.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true

anyhow.workspace = true
similar-asserts.workspace = true
starknet.workspace = true
tracing.workspace = true

# v6 types
katana-db-v1_2_2 = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.2", package = "katana-db" }
katana-primitives-v1_2_2 = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.2", package = "katana-primitives" }
katana-provider-v1_2_2 = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.2", package = "katana-provider" }

katana-db-v1_5_4 = { git = "https://github.com/dojoengine/katana", tag = "v1.5.4", package = "katana-db" }
katana-primitives-v1_5_4 = { git = "https://github.com/dojoengine/katana", tag = "v1.5.4", package = "katana-primitives" }
katana-provider-v1_5_4 = { git = "https://github.com/dojoengine/katana", tag = "v1.5.4", package = "katana-provider" }

[dev-dependencies]
katana-chain-spec.workspace = true
katana-log.workspace = true
tokio = { workspace = true, features = [ "full" ] }

fs_extra = "1.3.0"
tempfile.workspace = true
