[package]
build = "build.rs"
edition.workspace = true
license.workspace = true
name = "cartridge"
repository.workspace = true
version.workspace = true

[dependencies]
katana-chain-spec.workspace = true
katana-contracts.workspace = true
katana-core.workspace = true
katana-executor.workspace = true
katana-pool.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
katana-rpc-api.workspace = true
katana-rpc-server.workspace = true
katana-rpc-types.workspace = true
katana-tasks.workspace = true

anyhow.workspace = true
ark-ec = "0.4"
lazy_static.workspace = true
num-bigint.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true
# Use a specific revision of stark-vrf to avoid unwanted breaking changes.
stark-vrf = { git = "https://github.com/dojoengine/stark-vrf.git", rev = "96d6d2a" }

jsonrpsee = { workspace = true, features = [ "server" ] }
tower.workspace = true

cainome.workspace = true
cainome-cairo-serde.workspace = true

[dev-dependencies]
assert_matches.workspace = true
katana-node.workspace = true
katana-test-utils.workspace = true
katana-utils.workspace = true
mockito = "1.7.0"
similar-asserts.workspace = true
tokio.workspace = true
