[package]
name = "katana-tee"
description = "TEE (Trusted Execution Environment) support for Katana"
edition.workspace = true
version.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
bincode = { workspace = true, optional = true }
sev-snp = { workspace = true, optional = true }

[dev-dependencies]
rstest.workspace = true
tempfile.workspace = true

[features]
default = []
mock = []
snp = ["dep:sev-snp", "dep:bincode"]
