[package]
edition.workspace = true
license-file.workspace = true
name = "katana-paymaster"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
starknet.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3"

paymaster-prices = { git = "https://github.com/cartridge-gg/paymaster", branch = "copenhagen-4cb4", features = ["testing"] }
paymaster-relayer = { git = "https://github.com/cartridge-gg/paymaster", branch = "copenhagen-4cb4", features = ["testing"] }
paymaster-rpc = { git = "https://github.com/cartridge-gg/paymaster", branch = "copenhagen-4cb4" }
paymaster-sponsoring = { git = "https://github.com/cartridge-gg/paymaster", branch = "copenhagen-4cb4" }
paymaster-starknet = { git = "https://github.com/cartridge-gg/paymaster", branch = "copenhagen-4cb4" }
