name: Dev Image Test

on:
  pull_request:
    paths:
      - ".github/Dockerfile"

env:
  RUST_VERSION: 1.89.0
  CLIPPY_VERSION: nightly-2025-06-20

jobs:
  build-dev-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker build for ${{ matrix.platform }}
        uses: docker/build-push-action@v5
        with:
          push: false
          file: .github/Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            RUST_VERSION=${{ env.RUST_VERSION }}
            CLIPPY_VERSION=${{ env.CLIPPY_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
